# Theme App Extension: Featured Collection Grid
# Shows random products from a collection in a grid layout

api_version = "2024-10"

uid = "d71b01d3-dccb-3d16-1c2a-cc7818e5e0932046a4f7"

type = "theme_app_extension"

[settings]
